[package]
name = "prettyplease"
version = "0.1.25"
authors = ["David Tolnay <dtolnay@gmail.com>"]
autoexamples = false
categories = ["development-tools"]
description = "A minimal `syn` syntax tree pretty-printer"
documentation = "https://docs.rs/prettyplease"
edition = "2021"
exclude = ["cargo-expand"]
keywords = ["rustfmt"]
license = "MIT OR Apache-2.0"
links = "prettyplease01"
repository = "https://github.com/dtolnay/prettyplease"
rust-version = "1.56"

[features]
verbatim = ["syn/parsing"]

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
syn = { version = "1.0.90", default-features = false, features = ["full"] }

[dev-dependencies]
syn = { version = "1.0.90", default-features = false, features = ["parsing"] }

[lib]
doc-scrape-examples = false

[workspace]
members = ["cargo-expand/update", "examples/update"]
